language: php
php:
- 5.6

env:
  global:
    # Provider should be "pantheon" or "acquia"
  - PROVIDER="acquia"
  - secure: CvZOo6JcB8KH3yfeq2yLEX8aptJWSx5zaWM8jzF7u40hXuXjXwTwCo2YYMVoHpmEyBR1dbG+tffyDBn9GSa5WGwEaWUmCX600/IGXFpNxPTBS2GPDlcdKYQRUN9gH7mCPRW4vzCieYVmIedo3U1mut7U2Y3F4NZpLZgL4KG8/tJfhE9Q0oPlAohcjTMLOIx0uTOGW9ptficBD51bl53B9p5iQfw5apMNx3SwxmdGFQmvGyRAjwW9JXpqScwLPyIGsCtL0lmtQ/AegoJb8fTYBORnxTP2rQjjM5Pnr+w2nQ2lSkSbW0KADJyKVS9nCd12yKKRMUZKRC3bEpCxXHRwPRcD625r8UFrrCqg0iFn/Sct307KhIFdDD/TGcObTz2kR8jUnxphh2t62tUjhzeUN0FhZAGi6Bfl36Ap1sG1+A6xNgauNSUWP2yeReqkFaFlk6/sInV5Lh55xbInWU1SkbvJlC2TYULyFptAbNdbzY22YvNp2BHXjeuft5CMtjocvVPYZC71mRHH+FgYfpfT7aXNp/9/g+gqLDXp6N+azh4Q7wMYb8VAos7/M5s+QwjDWUJKt7aiWKBMnTeKHK+Tk+I1xwM0P+jsnr/Xkkmc2gcZJSDMKrXr4detqYZSbZFDDnIog2XCKWCgxl+R1Q/1YjO4306QdAN3HIGvhkJQU14=

before_install:
  - SCRIPTPATH="private/hooks/libraries/ci/$PROVIDER";
  - $SCRIPTPATH/set-directory.sh
  - openssl aes-256-cbc -K $encrypted_b7ec65ae1a29_key -iv $encrypted_b7ec65ae1a29_iv
    -in travisci_id_rsa.enc -out travisci_id_rsa -d
  - chmod 600 travisci_id_rsa
  - mv travisci_id_rsa ~/.ssh/id_rsa
  - composer self-update
  - export BASEDIR=${PWD}


install:
  - phpenv rehash
  - composer install
  - composer global require drush/drush:8.1.2
  - $SCRIPTPATH/install-dependencies.sh
  - composer global require behat/behat:3.*
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - mysql -e 'create database drupal;'

before_script:
  # This ensures that our terminus login won't hang on prompt.
  - echo "StrictHostKeyChecking no" > ~/.ssh/config
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`

  # Add our paas repo as an endpoint for pushes.
  - git remote add paas $PAASGIT

  - $SCRIPTPATH/pull-db.sh

  # Load our downloaded DB.
  - drush si --db-url=mysql://root@localhost/drupal -v -y
  - mysql -uroot drupal < db.sql

  # Run a webserver.
  - drush runserver 8080 - </dev/null &>$HOME/server.log &
  - cd ..
  - until cat $HOME/server.log | grep '8080'; do sleep 0.2; done

script:
  - cd $BASEDIR
  - behat

  - if [ $TRAVIS_BRANCH == 'master' ] && [ $TRAVIS_PULL_REQUEST == 'false' ]; then
      git fetch paas &&
      git merge -m "Merge changes to provider from github" paas/master &&
      git push paas HEAD:master;
    fi
