language: php
php:
- 5.6

env:
  global:
  # Provider should be "pantheon" or "acquia"
  - PROVIDER="acquia"
  # This should be the basepath. /docroot on Acquia, blank for Pantheon.
  - BASEPATH="/docroot"
  # This line provides the MACHINETOKEN value for authenticating with Terminus
  # on Pantheon. This value is associated with the travis ci user on Pantheon.
  - secure: X8dwKmT/iLn2xeehGU76IgKqLmf3kaSmG3Xme9SjkWZpM/KeJIugxeaTFQQkmgBMvbBqkKUcMfEP2/6aNzRTxGaSs6Fuj14T3Vj2W2zp6YAkmBm9KhxOEPTsKtSNqAfw9ZQHX2syaLe++bSpEDPlIGOQ6wUAtoVub6A+xcGiMr/QHyIpx1l8iivZMmzudXbKj6onz6fa3yPM6DDzBn2U1TD7g+IuuEERFr62LrbkxbDcya+X8pjThhMNixt/u3xeRDU/bldA0irZyTMCaZl3lUVhyUJLMdav6ORO5HR2l8917WVqd9eD81KnVHqm/zPSU+85q7Ix2IBNoZHtngl+ni58f8F1H/tEgScF4ROOWObS0GwmhWFvGyfPokpeZnR8c+wmATLJ8H1Qgx+kv9aAN0GQlVJROkiRSN0D2wXQLo0EAmxPSLbuEkweSKoZPPe9BUcXHShF1XlUkHe8INtDvl4Z1HuFyUJZwuEXHMXH86cndd03yxsJTvX/coXWcvqHwCY3TsHWtWqunSLdcazPHGU2ch5giepvM/4HNzxYSimxBrZjKSEgsMi+QlHFTXkhYOSbdX+mc3NxuFsoXbYBcVqVXGnr+Q0/LgtPVInjhpMlIXwOki5uQAjks57gJJf66cV01KTpHLcZnrHgBoxFmWPCeQOyHOY+w1U33xXiUnE=
  # This line provides the email account
  - secure: Rt1LSEgbltFPP3KXQC187hZpYLs+BlieKh1xVoSy4EHvrFYr1b5JuFdey0guTjxd2sWs6gUcBGTBX2dp+Na8ICr5h25V/5WaGjCUagM9mKMyThb9NDICmO8WFd19tAcsip6CbmEWqzAt158fB/1aa8ED05LHrFqZ8koCRRrpAfL/yrkP4jDNX/iDv2CBBqtiz1WjRrdhABfK4DxCtussrKTp8v24DosI2b/JYHfNlcF+nGFiQjku2s9wgMOcKr4HAjgAJ2Sv4TrxOpTzdca/dEKIWCDF8rqRediYyIyu79bNiDtbX+sehqSYCOYIcUbPqrZ9uBVheHlrVqc3AdDlPKLAJEcP6/POW0qHlGdNrcY2nAFPnwcgGAnmxW20VadKrvW9cnY3wJgDil72Y7IPiNhB6BoriLRJeL7xuv14F1K44o5mG8pp18QkjvmdgEVKBvC+WlbdEz4aQeEPZGMo4UcyVU5tGUq2HevEO3yHuv/xugWatho1TM/OyB2S7ifQEVxPd86fNowcLBZUPQDLv8o2yvZsn8sOCUmMg4yGjoS+GYCTLMVyeXX4E8p6TcgpfZ3fagOb8WKICZ58U5OeGBuq+0LvID/3hTZQPKU6U5qY8f4QXRoLqeK1mMlHyPJx0MKCwuzdOkOANIhXBCuPhxRoc/St8MS/qkjy1Y4yu5c=
  # This line provides the Acquia key
  - secure: Ag/O2sz/lF6pFVf80FJ53EcDIliCYxR693AOLyad0j6VOVO45KXwUALPbff+zBt+xgQaU8KSVMglRVSEnjCtTwK+GaWg2p6Q339yc1gHpomDCiandxnYrRrNl/mOjof48iB4BU0vtm8wcaw1ynNMiRwzpEhHjad1BmPnHObqi3x5L5aJy5M05rsi67JN7LiaGLzTaegvq5rShxxB31F9r5Ovq0jW3+OZvQhxx1782x+QFOWQEqSnJEjO9IzD11HsBzZCDLsQ1Ymr3zcFko0hQUasrU9t9OFrs1IJOKbKONaFP9Q4YZnqKUoKyfjWPgk/p+cGH5P06c21qfLTG8cpmqh4+t1hL5YRnuD+eSdrTDS/yJW4oroKVFGuo6WIrWAiyUYasbfNBi8m+Oc0tyxQovcCocuIQ/cTTbL3/qIk5RdvNr4VR2tSybUTHlaRnEWUlS7PZru7ej8eb0g7XWdaPHhT886mIi9wv6F0savZDBM0siPtFq4Pxgqbj/VLi6vByuY30UiVaYt0XwZ3szQJB91TYPyWUR8KyNr65EzwTakx95qK0WTHNvWh81DArQlDOySRpvFUWMX6pxbvqo94uupoVgBWtBnTvas4s4bohi9lckHpEZV7SV1PoOgQiEPzpJVnBtgcEzevpI9FsT5fMiS0mntaGHK3atJSWc8lgKY=

before_install:
  # You'll need to generate this line by creating an ssh key and then encrypting.
  # Name the file travisci_id_rsa and encrypt with travis encrypt-file travisci_id_rsa --add
  # This will encrypt the file, create the variables, and add this line to your
  # .travis.yml file.
  - openssl aes-256-cbc -K $encrypted_9b4e19b001bc_key -iv $encrypted_9b4e19b001bc_iv
    -in travisci_id_rsa.enc -out travisci_id_rsa -d
  - chmod 600 travisci_id_rsa
  - mv travisci_id_rsa ~/.ssh/id_rsa

  # This ensures that our ssh/terminus login won't hang on prompt.
  - echo "StrictHostKeyChecking no" > ~/.ssh/config

  # Define script path and our Drupal root.
  - SCRIPTPATH="${PWD}/private/hooks/libraries/ci/$PROVIDER";
  - export BASEDIR="${PWD}$BASEPATH"
  - cd $BASEDIR
  - echo ${PWD}
  # - composer self-update

install:
  - cd $BASEDIR
  # - export PATH="$HOME/.composer/vendor/bin:$PATH"
  # - phpenv rehash
  # - composer update
  # - composer install
  # - composer global require drush/drush:8.1.2
  - $SCRIPTPATH/install-dependencies.sh
  - composer global require behat/behat:3.*
  - mysql -e 'create database drupal;'

before_script:
  - cd $BASEDIR
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`

  # Add our paas repo as an endpoint for pushes.
  - git remote add paas $PAASGIT

  - $SCRIPTPATH/pull-db.sh

  # Load our downloaded DB.
  - drush si --db-url=mysql://root@localhost/drupal -v -y
  - mysql -uroot drupal < db.sql

  # Run a webserver.
  - drush runserver 8080 - </dev/null &>$HOME/server.log &
  - cd ..
  - until cat $HOME/server.log | grep '8080'; do sleep 0.2; done

script:
  - cd $BASEDIR
  - behat

  - if [ $TRAVIS_BRANCH == 'master' ] && [ $TRAVIS_PULL_REQUEST == 'false' ]; then
      git fetch paas &&
      git merge -m "Merge changes to provider from github" paas/master &&
      git push paas HEAD:master;
    fi
